apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-app-yxvf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-app-yxvf
    app.kubernetes.io/part-of: my-application-1
  name: demo-app-yxvf
  namespace: karthik
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo-app-yxvf
    weight: 100
status: {}
