apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-application-1
    appstudio.openshift.io/component: demo-app-yxvf
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: demo-app-yxvf
  namespace: karthik
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_karthikjeeyar_demo-app
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/karthikjeeyar/demo-app
